MQTT_WEBSOCKET_URL = "wss://wss-eu-uk1.ws-amazon.com/mqtt"
MQTT_WEBSOCKET_SUBPROTOCOL = "mqtt"

MQTT_PROTOCOL_NAME = "MQTT"
MQTT_PROTOCOL_LEVEL = 4

MQTT_KEEP_ALIVE_SECONDS = 60
MQTT_CLEAN_SESSION = True